spring.application.name=FinPilot

spring.profiles.active=local

# May delete later
logging.level.org.springframework.security=DEBUG

#Secret Key for JWT token
jwt.secret=your-very-long-secret-key-for-finpilot
jwt.expiration=86400000